//export const columns1 = [
//  {
//      key: 'name',
//      title: '姓名'
//  },
//  {
//      key: 'tel',
//      title: '电话号码'
//  }
//];s

export const searchTable1 = [
     {
					work:'系统管理',
					name:'admin',
					date:'2013-11-11',
					index:'1'
				},
				{
					work:'财务管理',
					name:'admin',
					date:'2013-11-11',
					index:'2'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'3'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'4'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'5'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'6'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'7'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'8'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
				{
					work:'运营负责人',
					name:'linxy',
					date:'2013-11-11',
					index:'9'
				},
];




